import React from "react";
import { forwardRef } from "react";
import styles from "./GenerateInvoiceImage.module.scss";

const GenerateInvoiceHtml = forwardRef((props, ref) => {
  return (
    <div ref={ref} className={styles['invoice-img']}>
      <div className={styles['header-cont']}>
        <h1 className={styles['main-header']}>INVOICE</h1>
        <div className={styles['invoice-id']}>
          <h4 className={styles['id-head']}>INVOICE #</h4>
          <p className="id-content">{props.invoiceID}</p>
        </div>
      </div>
      <div className="date-cont">
        <h3>DATE:</h3>
        <h3 className="date">{props.date}</h3>
      </div>
      <div className="role-details">
        <h2 className="role-head">SELLER DETAILS</h2>
        <div className="flex-row">
          <h3 className="role-n">NAME:</h3>
          <p className="role-nf">{props.sellerName}</p>
        </div>
        <div className="flex-row">
          <h3 className="role-n">PAN:</h3>
          <p className="role-nf">{props.sellerPan}</p>
        </div>
      </div>
      <div className="role-details">
        <h2 className="role-head">BILLING TO:</h2>
        <div className="flex-row">
          <h3 className="role-n">NAME:</h3>
          <p className="role-nf">{props.buyerName}</p>
        </div>
        <div className="flex-row">
          <h3 className="role-n">PAN:</h3>
          <p className="role-nf">{props.buyerPan}</p>
        </div>
      </div>
      <div className="amt-cont">
        <h3 className="role-n">AMOUNT:</h3>
        <h3>{props.amount}</h3>
      </div>
      <div className="status-cont">
        <h3 className="role-n">STATUS:</h3>
        <h3>{props.status}</h3>
      </div>
      <div className="status-cont">
        <h3 className="role-n">MONTHS LEFT:</h3>
        <h3>{props.monthsLeft}</h3>
      </div>
      <div className="footer">
        <p className="footer-text">
          Auto-generated by <span className="logo">Duckounting ©</span>
        </p>
      </div>
    </div>
  );
});

// const GenerateInvoiceImage = (props) => {
// return (
//   <div class="modal" tabindex="-1" role="dialog">
//     <div class="modal-dialog" role="document">
//       <div class="modal-content">
//         <div class="modal-header">
//           <h5 class="modal-title">Generate Invoice Image</h5>
//           <button
//             type="button"
//             class="close"
//             data-dismiss="modal"
//             aria-label="Close"
//           >
//             <span aria-hidden="true">&times;</span>
//           </button>
//         </div>
//         <div class="modal-body">
//           <GenerateInvoiceHtml ref={ref} props={props} />
//         </div>
//         <div class="modal-footer">
//           <button type="button" class="btn btn-primary">
//             Generate Image
//           </button>
//         </div>
//       </div>
//     </div>
//   </div>
// );
// };

export default GenerateInvoiceHtml;
